src/Entity/Book.php
<?php

namespace App\Entity;

use App\Repository\BookRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: BookRepository::class)]
class Book
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $description = null;

    #[ORM\Column]
    private ?int $pages = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $publication_date = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $created_at = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $updated_at = null;

    #[ORM\ManyToOne(targetEntity: Category::class, inversedBy: 'books')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Category $category = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getPages(): ?int
    {
        return $this->pages;
    }

    public function setPages(int $pages): static
    {
        $this->pages = $pages;

        return $this;
    }

    public function getPublicationDate(): ?\DateTimeInterface
    {
        return $this->publication_date;
    }

    public function setPublicationDate(\DateTimeInterface $publication_date): static
    {
        $this->publication_date = $publication_date;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): static
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeInterface $updated_at): static
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): static
    {
        $this->category = $category;

        return $this;
    }
}

src/Controller/HomeController.php
<?php
namespace App\Controller;

use App\Repository\BookReadRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Bundle\SecurityBundle\Security;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Repository\BookRepository;

class HomeController extends AbstractController
{
    private BookReadRepository $readBookRepository;

    // Inject the repository via the constructor
    public function __construct(BookReadRepository $bookReadRepository, private readonly Security $security)
    {
        $this->readBookRepository = $bookReadRepository;
    }

    #[Route('/', name: 'app.home')]
    public function index(BookRepository $bookRepository): Response
    {
        $user = $this->getUser();

        if (!$user) {
            // Utilisation de la méthode redirectToRoute pour rediriger vers la page de connexion
            return $this->redirectToRoute('auth.login');
        }
        // Récupère toutes les lectures (pas uniquement celles lues)
        $allBooksRead = $this->readBookRepository->findByUserId($user->getId(), false);
        
        // Récupère uniquement les livres lus
        $booksReadCompleted = $this->readBookRepository->findReadBooksByUserId($user->getId());
    
        $email = $this->security->getUser()->getUserIdentifier();
        $books = $bookRepository->findAll();
        
        return $this->render('pages/home.html.twig', [
            'allBooksRead' => $allBooksRead, 
            'booksReadCompleted' => $booksReadCompleted, // Spécifique au composant
            'name' => 'Accueil',
            'email' => $email,
            'books' => $books,
        ]);
    }
}

templates/components/home/booksRead.html.twig
<div class="card card-grid h-full min-w-full">
    <div class="card-header">
        <h3 class="card-title">
            Mes lectures terminées
        </h3>
        <div class="input input-sm max-w-48">
            <i class="ki-filled ki-magnifier"></i>
            <input data-datatable-search="#read-books-table" placeholder="Rechercher" type="text"/>
        </div>
    </div>
    <div class="card-body">
        <div id="read-books-table" data-datatable="true" data-datatable-page-size="5">
            <div class="scrollable-x-auto">
                <table class="table table-border" data-datatable-table="true">
                    <thead>
                        <tr>
                            <th class="min-w-[280px]">
                                <span class="sort asc">
                                    <span class="sort-label">Livre</span>
                                    <span class="sort-icon"></span>
                                </span>
                            </th>
                            <th class="min-w-[135px]">
                                <span class="sort asc">
                                    <span class="sort-label">Catégorie</span>
                                    <span class="sort-icon"></span>
                                </span>
                            </th>
                            <th class="min-w-[135px]">
                                <span class="sort asc">
                                    <span class="sort-label">Note</span>
                                    <span class="sort-icon"></span>
                                </span>
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for bookRead in booksReadCompleted  %}
                            <tr>
                                <td>
                                    <div class="flex flex-col gap-2">
                                        <a class="leading-none font-medium text-sm text-gray-900 hover:text-primary" href="#">
                                            <h3>{{ bookRead.book.name }}</h3> <!-- Nom du livre -->
                                        </a>
                                        <span class="text-2sm text-gray-700 font-normal leading-3">
                                            <h3>{{ bookRead.book.description }}</h3> <!-- Description du livre -->
                                        </span>
                                    </div>
                                </td>

                                <td>
                                    {# Affichage de la catégorie du livre #}
                                    {% if bookRead.book.category %}
                                        {{ bookRead.book.category.name }}
                                    {% else %}
                                        <span>Aucune catégorie</span>
                                    {% endif %}
                                </td>

                                <td>
                                    <div class="rating">
                                        {% for i in 1..5 %}
                                            {% if i <= bookRead.rating %}
                                                <i class="rating-on ki-solid ki-star text-base leading-none"></i>
                                            {% else %}
                                                <i class="rating-off ki-outline ki-star text-base leading-none"></i> 
                                            {% endif %}
                                        {% endfor %}
                                    </div>
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            <div class="card-footer justify-center md:justify-between flex-col md:flex-row gap-5 text-gray-600 text-2sm font-medium">
                <div class="flex items-center gap-2 order-2 md:order-1">
                    Show
                    <select class="select select-sm w-16" data-datatable-size="true" name="perpage"></select>
                    per page
                </div>
                <div class="flex items-center gap-4 order-1 md:order-2">
                    <span data-datatable-info="true"></span>
                    <div class="pagination" data-datatable-pagination="true"></div>
                </div>
            </div>
        </div>
    </div>
</div>

templates/components/home/booksReading.html.twig
<div class="card card-grid h-full min-w-full">
    <div class="card-header">
        <h3 class="card-title">
            Mes lectures en cours
        </h3>
        <div class="input input-sm max-w-48">
            <i class="ki-filled ki-magnifier">
            </i>
            <input data-datatable-search="#current-books-table" placeholder="Rechercher" type="text"/>
        </div>
    </div>
    <div class="card-body">
        <div id="current-books-table" data-datatable="true" data-datatable-page-size="5">
            <div class="scrollable-x-auto">
                <table  id="booksTable" class="table table-border" data-datatable-table="true">
                    <thead>
                    <tr>
                        <th class="min-w-[280px]">
                            <span class="sort asc">
                                <span class="sort-label">Livre</span>
                                <span class="sort-icon"></span>
                            </span>
                        </th>
                        <th class="max-w-[135px] text-end">
                            <span class="sort">
                                <span class="sort-label">Modifié le</span>
                                <span class="sort-icon"></span>
                            </span>
                        </th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for bookRead in allBooksRead  %}
                        <tr>
                            <td>
                                <div class="flex flex-col gap-2">
                                    <a class="leading-none font-medium text-sm text-gray-900 hover:text-primary"
                                       href="#">
                                        <h3>{{ bookRead.book.name }}</h3> 
                                    </a>
                                    <span class="text-2sm text-gray-700 font-normal leading-3">
                                   <p>{{ bookRead.book.description }}</p> 
                                </span>
                                <button class="btn btn-edit" data-id="{{ bookRead.id }}">Modifier</button>
                                </div>
                            </td>
                            <td class="text-end">
                                {{ bookRead.updatedAt|date('d/m/Y à H:i') }}
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
            <div class="card-footer justify-center md:justify-between flex-col md:flex-row gap-5 text-gray-600 text-2sm font-medium">
                <div class="flex items-center gap-4 order-1 md:order-2">
                    <span data-datatable-info="true"></span>
                    <div class="pagination" data-datatable-pagination="true"></div>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
document.querySelectorAll('.btn-edit').forEach(button => {
    button.addEventListener('click', function () {
        const bookId = this.getAttribute('data-id');
        fetch(`/api/book-read/${bookId}`)
            .then(response => response.json())
            .then(data => {
                document.getElementById('book').value = data.bookId;
                document.getElementById('description').value = data.description;
                document.getElementById('rating').value = data.rating;
                document.getElementById('check').checked = data.isRead;

                const form = document.getElementById('bookReadForm');
                form.action = `/edit-book-read/${bookId}`;
                document.getElementById('book_modal').classList.add('open');
            });
    });
});

document.getElementById('bookReadForm').addEventListener('submit', function (event) {
    event.preventDefault();
    const formData = new FormData(this);
    fetch(this.action, {
        method: 'POST',
        body: formData,
    })
        .then(response => response.json())
        .then(data => {
            if (data.error) {
                alert(data.error);
            } else {
                // Mettre à jour le tableau
                location.reload();
            }
        });
});
</script>

templates/components/home/radarChart.html.twig
<div class="card h-full">
    <div class="card-header">
        <h3 class="card-title">Répartition de mes lectures</h3>
    </div>
    <div class="card-body flex flex-col gap-5">
        <div id="radarChart"></div> <!-- id graphique  -->
    </div>
</div>
<script>
document.addEventListener('DOMContentLoaded', () => {
    fetch('/api/categories-data')
        .then(response => response.json())
        .then(data => {
            const options = {
                chart: {
                    type: 'radar',
                    height: 350,
                },
                series: [{
                    name: 'Nombre d\'éléments',
                    data: data.series,
                }],
                xaxis: {
                    categories: data.categories,
                },
                title: {
                    text: 'Répartition des catégories',
                },
            };

            const chart = new ApexCharts(document.querySelector('#radarChart'), options);
            chart.render();
        })
        .catch(error => console.error('erreur radar :', error));
});
</script>